export const bonnaDepartments=[
    {name: "ArGe&Proses"},
    {name: "Bakım ve Enerji"},
    {name: "Bilgi Teknolojileri"},
    {name: "Dış Ticaret"},
    {name: "Dijital Dönüşüm"},
    {name: "Dijital Tasarım"},
    {name: "Finans"},
    {name: "Hammadde Hazırlama"},
    {name: "İdari İşler"},
    {name: "İnsan Kaynakları"},
    {name: "İnsan Kaynakları ve İdari İşler"},
    {name: "Kalite Güvence"},
    {name: "Kilit Müşteri"},
    {name: "Lojistik"},
    {name: "Mali İşler"},
    {name: "Metot/Opex"},
    {name: "Muhasebe"},
    {name: "Planlama"},
    {name: "Satın Alma"},
    {name: "Tedarik Zinciri"},
    {name: "Ticari Pazarlama"},
    {name: "Üretim"},
    {name: "Yurtiçi Satış"}
]